apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-deploy
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deploy
  targetCPUUtilizationPercentage: 60
